// Generated by gencpp from file gs_vision/Apriltag.msg
// DO NOT EDIT!


#ifndef GS_VISION_MESSAGE_APRILTAG_H
#define GS_VISION_MESSAGE_APRILTAG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gs_vision
{
template <class ContainerAllocator>
struct Apriltag_
{
  typedef Apriltag_<ContainerAllocator> Type;

  Apriltag_()
    : tag_family()
    , tag_id(0)
    , hamming(0)
    , goodness(0.0)
    , decision_margin(0.0)
    , center_x(0.0)
    , center_y(0.0)
    , x1(0.0)
    , y1(0.0)
    , x2(0.0)
    , y2(0.0)
    , x3(0.0)
    , y3(0.0)
    , x4(0.0)
    , y4(0.0)  {
    }
  Apriltag_(const ContainerAllocator& _alloc)
    : tag_family(_alloc)
    , tag_id(0)
    , hamming(0)
    , goodness(0.0)
    , decision_margin(0.0)
    , center_x(0.0)
    , center_y(0.0)
    , x1(0.0)
    , y1(0.0)
    , x2(0.0)
    , y2(0.0)
    , x3(0.0)
    , y3(0.0)
    , x4(0.0)
    , y4(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _tag_family_type;
  _tag_family_type tag_family;

   typedef int32_t _tag_id_type;
  _tag_id_type tag_id;

   typedef int32_t _hamming_type;
  _hamming_type hamming;

   typedef float _goodness_type;
  _goodness_type goodness;

   typedef float _decision_margin_type;
  _decision_margin_type decision_margin;

   typedef float _center_x_type;
  _center_x_type center_x;

   typedef float _center_y_type;
  _center_y_type center_y;

   typedef float _x1_type;
  _x1_type x1;

   typedef float _y1_type;
  _y1_type y1;

   typedef float _x2_type;
  _x2_type x2;

   typedef float _y2_type;
  _y2_type y2;

   typedef float _x3_type;
  _x3_type x3;

   typedef float _y3_type;
  _y3_type y3;

   typedef float _x4_type;
  _x4_type x4;

   typedef float _y4_type;
  _y4_type y4;





  typedef boost::shared_ptr< ::gs_vision::Apriltag_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gs_vision::Apriltag_<ContainerAllocator> const> ConstPtr;

}; // struct Apriltag_

typedef ::gs_vision::Apriltag_<std::allocator<void> > Apriltag;

typedef boost::shared_ptr< ::gs_vision::Apriltag > ApriltagPtr;
typedef boost::shared_ptr< ::gs_vision::Apriltag const> ApriltagConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gs_vision::Apriltag_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gs_vision::Apriltag_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gs_vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'gs_vision': ['/home/ubuntu/geoscan_ws/src/gs_vision/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::gs_vision::Apriltag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gs_vision::Apriltag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gs_vision::Apriltag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gs_vision::Apriltag_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gs_vision::Apriltag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gs_vision::Apriltag_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gs_vision::Apriltag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1e422dacce6e2d78bb582e8091769fc8";
  }

  static const char* value(const ::gs_vision::Apriltag_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1e422dacce6e2d78ULL;
  static const uint64_t static_value2 = 0xbb582e8091769fc8ULL;
};

template<class ContainerAllocator>
struct DataType< ::gs_vision::Apriltag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gs_vision/Apriltag";
  }

  static const char* value(const ::gs_vision::Apriltag_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gs_vision::Apriltag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string tag_family\n"
"int32 tag_id\n"
"int32 hamming\n"
"float32 goodness\n"
"float32 decision_margin\n"
"float32 center_x\n"
"float32 center_y\n"
"float32 x1\n"
"float32 y1\n"
"float32 x2\n"
"float32 y2\n"
"float32 x3\n"
"float32 y3\n"
"float32 x4\n"
"float32 y4\n"
;
  }

  static const char* value(const ::gs_vision::Apriltag_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gs_vision::Apriltag_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tag_family);
      stream.next(m.tag_id);
      stream.next(m.hamming);
      stream.next(m.goodness);
      stream.next(m.decision_margin);
      stream.next(m.center_x);
      stream.next(m.center_y);
      stream.next(m.x1);
      stream.next(m.y1);
      stream.next(m.x2);
      stream.next(m.y2);
      stream.next(m.x3);
      stream.next(m.y3);
      stream.next(m.x4);
      stream.next(m.y4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Apriltag_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gs_vision::Apriltag_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gs_vision::Apriltag_<ContainerAllocator>& v)
  {
    s << indent << "tag_family: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.tag_family);
    s << indent << "tag_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tag_id);
    s << indent << "hamming: ";
    Printer<int32_t>::stream(s, indent + "  ", v.hamming);
    s << indent << "goodness: ";
    Printer<float>::stream(s, indent + "  ", v.goodness);
    s << indent << "decision_margin: ";
    Printer<float>::stream(s, indent + "  ", v.decision_margin);
    s << indent << "center_x: ";
    Printer<float>::stream(s, indent + "  ", v.center_x);
    s << indent << "center_y: ";
    Printer<float>::stream(s, indent + "  ", v.center_y);
    s << indent << "x1: ";
    Printer<float>::stream(s, indent + "  ", v.x1);
    s << indent << "y1: ";
    Printer<float>::stream(s, indent + "  ", v.y1);
    s << indent << "x2: ";
    Printer<float>::stream(s, indent + "  ", v.x2);
    s << indent << "y2: ";
    Printer<float>::stream(s, indent + "  ", v.y2);
    s << indent << "x3: ";
    Printer<float>::stream(s, indent + "  ", v.x3);
    s << indent << "y3: ";
    Printer<float>::stream(s, indent + "  ", v.y3);
    s << indent << "x4: ";
    Printer<float>::stream(s, indent + "  ", v.x4);
    s << indent << "y4: ";
    Printer<float>::stream(s, indent + "  ", v.y4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GS_VISION_MESSAGE_APRILTAG_H
