# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from gs_vision/QR_array.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import gs_vision.msg

class QR_array(genpy.Message):
  _md5sum = "c2cc8666bc7a2bbd9d5b119ac5932231"
  _type = "gs_vision/QR_array"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """QR[] qrs
================================================================================
MSG: gs_vision/QR
string data
int32 left
int32 top
int32 width
int32 height
int32 x1
int32 y1
int32 x2
int32 y2
int32 x3
int32 y3
int32 x4
int32 y4"""
  __slots__ = ['qrs']
  _slot_types = ['gs_vision/QR[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       qrs

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(QR_array, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.qrs is None:
        self.qrs = []
    else:
      self.qrs = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.qrs)
      buff.write(_struct_I.pack(length))
      for val1 in self.qrs:
        _x = val1.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_get_struct_12i().pack(_x.left, _x.top, _x.width, _x.height, _x.x1, _x.y1, _x.x2, _x.y2, _x.x3, _x.y3, _x.x4, _x.y4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.qrs is None:
        self.qrs = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.qrs = []
      for i in range(0, length):
        val1 = gs_vision.msg.QR()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.data = str[start:end].decode('utf-8')
        else:
          val1.data = str[start:end]
        _x = val1
        start = end
        end += 48
        (_x.left, _x.top, _x.width, _x.height, _x.x1, _x.y1, _x.x2, _x.y2, _x.x3, _x.y3, _x.x4, _x.y4,) = _get_struct_12i().unpack(str[start:end])
        self.qrs.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.qrs)
      buff.write(_struct_I.pack(length))
      for val1 in self.qrs:
        _x = val1.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_get_struct_12i().pack(_x.left, _x.top, _x.width, _x.height, _x.x1, _x.y1, _x.x2, _x.y2, _x.x3, _x.y3, _x.x4, _x.y4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.qrs is None:
        self.qrs = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.qrs = []
      for i in range(0, length):
        val1 = gs_vision.msg.QR()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.data = str[start:end].decode('utf-8')
        else:
          val1.data = str[start:end]
        _x = val1
        start = end
        end += 48
        (_x.left, _x.top, _x.width, _x.height, _x.x1, _x.y1, _x.x2, _x.y2, _x.x3, _x.y3, _x.x4, _x.y4,) = _get_struct_12i().unpack(str[start:end])
        self.qrs.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12i = None
def _get_struct_12i():
    global _struct_12i
    if _struct_12i is None:
        _struct_12i = struct.Struct("<12i")
    return _struct_12i
