// Generated by gencpp from file gs_service/EventRequest.msg
// DO NOT EDIT!


#ifndef GS_SERVICE_MESSAGE_EVENTREQUEST_H
#define GS_SERVICE_MESSAGE_EVENTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gs_service
{
template <class ContainerAllocator>
struct EventRequest_
{
  typedef EventRequest_<ContainerAllocator> Type;

  EventRequest_()
    : event(0)  {
    }
  EventRequest_(const ContainerAllocator& _alloc)
    : event(0)  {
  (void)_alloc;
    }



   typedef int32_t _event_type;
  _event_type event;





  typedef boost::shared_ptr< ::gs_service::EventRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gs_service::EventRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EventRequest_

typedef ::gs_service::EventRequest_<std::allocator<void> > EventRequest;

typedef boost::shared_ptr< ::gs_service::EventRequest > EventRequestPtr;
typedef boost::shared_ptr< ::gs_service::EventRequest const> EventRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gs_service::EventRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gs_service::EventRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gs_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': True, 'HasHeader': False}
// {'gs_service': ['/home/ubuntu/geoscan_ws/src/gs_service/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::gs_service::EventRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gs_service::EventRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gs_service::EventRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gs_service::EventRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gs_service::EventRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gs_service::EventRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gs_service::EventRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b2a9c605bb7a420089b02c6063322298";
  }

  static const char* value(const ::gs_service::EventRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb2a9c605bb7a4200ULL;
  static const uint64_t static_value2 = 0x89b02c6063322298ULL;
};

template<class ContainerAllocator>
struct DataType< ::gs_service::EventRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gs_service/EventRequest";
  }

  static const char* value(const ::gs_service::EventRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gs_service::EventRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 event\n"
"\n"
;
  }

  static const char* value(const ::gs_service::EventRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gs_service::EventRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.event);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EventRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gs_service::EventRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gs_service::EventRequest_<ContainerAllocator>& v)
  {
    s << indent << "event: ";
    Printer<int32_t>::stream(s, indent + "  ", v.event);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GS_SERVICE_MESSAGE_EVENTREQUEST_H
