// Generated by gencpp from file gs_service/LogResponse.msg
// DO NOT EDIT!


#ifndef GS_SERVICE_MESSAGE_LOGRESPONSE_H
#define GS_SERVICE_MESSAGE_LOGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gs_service
{
template <class ContainerAllocator>
struct LogResponse_
{
  typedef LogResponse_<ContainerAllocator> Type;

  LogResponse_()
    : msgs()  {
    }
  LogResponse_(const ContainerAllocator& _alloc)
    : msgs(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _msgs_type;
  _msgs_type msgs;





  typedef boost::shared_ptr< ::gs_service::LogResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gs_service::LogResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LogResponse_

typedef ::gs_service::LogResponse_<std::allocator<void> > LogResponse;

typedef boost::shared_ptr< ::gs_service::LogResponse > LogResponsePtr;
typedef boost::shared_ptr< ::gs_service::LogResponse const> LogResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gs_service::LogResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gs_service::LogResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gs_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'gs_service': ['/home/ubuntu/geoscan_ws/src/gs_service/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::gs_service::LogResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gs_service::LogResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gs_service::LogResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gs_service::LogResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gs_service::LogResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gs_service::LogResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gs_service::LogResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "52d4db86eb00b72e64733ff4ed17355d";
  }

  static const char* value(const ::gs_service::LogResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x52d4db86eb00b72eULL;
  static const uint64_t static_value2 = 0x64733ff4ed17355dULL;
};

template<class ContainerAllocator>
struct DataType< ::gs_service::LogResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gs_service/LogResponse";
  }

  static const char* value(const ::gs_service::LogResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gs_service::LogResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"string[] msgs\n"
;
  }

  static const char* value(const ::gs_service::LogResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gs_service::LogResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msgs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LogResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gs_service::LogResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gs_service::LogResponse_<ContainerAllocator>& v)
  {
    s << indent << "msgs[]" << std::endl;
    for (size_t i = 0; i < v.msgs.size(); ++i)
    {
      s << indent << "  msgs[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msgs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GS_SERVICE_MESSAGE_LOGRESPONSE_H
