// Generated by gencpp from file gs_service/LpsPosResponse.msg
// DO NOT EDIT!


#ifndef GS_SERVICE_MESSAGE_LPSPOSRESPONSE_H
#define GS_SERVICE_MESSAGE_LPSPOSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gs_service
{
template <class ContainerAllocator>
struct LpsPosResponse_
{
  typedef LpsPosResponse_<ContainerAllocator> Type;

  LpsPosResponse_()
    : lpsX(0.0)
    , lpsY(0.0)
    , lpsZ(0.0)  {
    }
  LpsPosResponse_(const ContainerAllocator& _alloc)
    : lpsX(0.0)
    , lpsY(0.0)
    , lpsZ(0.0)  {
  (void)_alloc;
    }



   typedef float _lpsX_type;
  _lpsX_type lpsX;

   typedef float _lpsY_type;
  _lpsY_type lpsY;

   typedef float _lpsZ_type;
  _lpsZ_type lpsZ;





  typedef boost::shared_ptr< ::gs_service::LpsPosResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gs_service::LpsPosResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LpsPosResponse_

typedef ::gs_service::LpsPosResponse_<std::allocator<void> > LpsPosResponse;

typedef boost::shared_ptr< ::gs_service::LpsPosResponse > LpsPosResponsePtr;
typedef boost::shared_ptr< ::gs_service::LpsPosResponse const> LpsPosResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gs_service::LpsPosResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gs_service::LpsPosResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gs_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': True, 'HasHeader': False}
// {'gs_service': ['/home/ubuntu/geoscan_ws/src/gs_service/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::gs_service::LpsPosResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gs_service::LpsPosResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gs_service::LpsPosResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gs_service::LpsPosResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gs_service::LpsPosResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gs_service::LpsPosResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gs_service::LpsPosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "28576301d1e7ebfaeb880e74c20055fe";
  }

  static const char* value(const ::gs_service::LpsPosResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x28576301d1e7ebfaULL;
  static const uint64_t static_value2 = 0xeb880e74c20055feULL;
};

template<class ContainerAllocator>
struct DataType< ::gs_service::LpsPosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gs_service/LpsPosResponse";
  }

  static const char* value(const ::gs_service::LpsPosResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gs_service::LpsPosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"float32 lpsX\n"
"float32 lpsY\n"
"float32 lpsZ\n"
;
  }

  static const char* value(const ::gs_service::LpsPosResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gs_service::LpsPosResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lpsX);
      stream.next(m.lpsY);
      stream.next(m.lpsZ);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LpsPosResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gs_service::LpsPosResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gs_service::LpsPosResponse_<ContainerAllocator>& v)
  {
    s << indent << "lpsX: ";
    Printer<float>::stream(s, indent + "  ", v.lpsX);
    s << indent << "lpsY: ";
    Printer<float>::stream(s, indent + "  ", v.lpsY);
    s << indent << "lpsZ: ";
    Printer<float>::stream(s, indent + "  ", v.lpsZ);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GS_SERVICE_MESSAGE_LPSPOSRESPONSE_H
