// Generated by gencpp from file gs_service/LpsVel.msg
// DO NOT EDIT!


#ifndef GS_SERVICE_MESSAGE_LPSVEL_H
#define GS_SERVICE_MESSAGE_LPSVEL_H

#include <ros/service_traits.h>


#include <gs_service/LpsVelRequest.h>
#include <gs_service/LpsVelResponse.h>


namespace gs_service
{

struct LpsVel
{

typedef LpsVelRequest Request;
typedef LpsVelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LpsVel
} // namespace gs_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gs_service::LpsVel > {
  static const char* value()
  {
    return "81c82ec0d0933ca8027062009ab83047";
  }

  static const char* value(const ::gs_service::LpsVel&) { return value(); }
};

template<>
struct DataType< ::gs_service::LpsVel > {
  static const char* value()
  {
    return "gs_service/LpsVel";
  }

  static const char* value(const ::gs_service::LpsVel&) { return value(); }
};


// service_traits::MD5Sum< ::gs_service::LpsVelRequest> should match 
// service_traits::MD5Sum< ::gs_service::LpsVel > 
template<>
struct MD5Sum< ::gs_service::LpsVelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gs_service::LpsVel >::value();
  }
  static const char* value(const ::gs_service::LpsVelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gs_service::LpsVelRequest> should match 
// service_traits::DataType< ::gs_service::LpsVel > 
template<>
struct DataType< ::gs_service::LpsVelRequest>
{
  static const char* value()
  {
    return DataType< ::gs_service::LpsVel >::value();
  }
  static const char* value(const ::gs_service::LpsVelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gs_service::LpsVelResponse> should match 
// service_traits::MD5Sum< ::gs_service::LpsVel > 
template<>
struct MD5Sum< ::gs_service::LpsVelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gs_service::LpsVel >::value();
  }
  static const char* value(const ::gs_service::LpsVelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gs_service::LpsVelResponse> should match 
// service_traits::DataType< ::gs_service::LpsVel > 
template<>
struct DataType< ::gs_service::LpsVelResponse>
{
  static const char* value()
  {
    return DataType< ::gs_service::LpsVel >::value();
  }
  static const char* value(const ::gs_service::LpsVelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GS_SERVICE_MESSAGE_LPSVEL_H
