// Generated by gencpp from file gs_service/Pos.msg
// DO NOT EDIT!


#ifndef GS_SERVICE_MESSAGE_POS_H
#define GS_SERVICE_MESSAGE_POS_H

#include <ros/service_traits.h>


#include <gs_service/PosRequest.h>
#include <gs_service/PosResponse.h>


namespace gs_service
{

struct Pos
{

typedef PosRequest Request;
typedef PosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Pos
} // namespace gs_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gs_service::Pos > {
  static const char* value()
  {
    return "0c725f9e77c9ba3d3e173571341a5f71";
  }

  static const char* value(const ::gs_service::Pos&) { return value(); }
};

template<>
struct DataType< ::gs_service::Pos > {
  static const char* value()
  {
    return "gs_service/Pos";
  }

  static const char* value(const ::gs_service::Pos&) { return value(); }
};


// service_traits::MD5Sum< ::gs_service::PosRequest> should match 
// service_traits::MD5Sum< ::gs_service::Pos > 
template<>
struct MD5Sum< ::gs_service::PosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gs_service::Pos >::value();
  }
  static const char* value(const ::gs_service::PosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gs_service::PosRequest> should match 
// service_traits::DataType< ::gs_service::Pos > 
template<>
struct DataType< ::gs_service::PosRequest>
{
  static const char* value()
  {
    return DataType< ::gs_service::Pos >::value();
  }
  static const char* value(const ::gs_service::PosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gs_service::PosResponse> should match 
// service_traits::MD5Sum< ::gs_service::Pos > 
template<>
struct MD5Sum< ::gs_service::PosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gs_service::Pos >::value();
  }
  static const char* value(const ::gs_service::PosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gs_service::PosResponse> should match 
// service_traits::DataType< ::gs_service::Pos > 
template<>
struct DataType< ::gs_service::PosResponse>
{
  static const char* value()
  {
    return DataType< ::gs_service::Pos >::value();
  }
  static const char* value(const ::gs_service::PosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GS_SERVICE_MESSAGE_POS_H
