// Generated by gencpp from file gs_service/PosGPS.msg
// DO NOT EDIT!


#ifndef GS_SERVICE_MESSAGE_POSGPS_H
#define GS_SERVICE_MESSAGE_POSGPS_H

#include <ros/service_traits.h>


#include <gs_service/PosGPSRequest.h>
#include <gs_service/PosGPSResponse.h>


namespace gs_service
{

struct PosGPS
{

typedef PosGPSRequest Request;
typedef PosGPSResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PosGPS
} // namespace gs_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gs_service::PosGPS > {
  static const char* value()
  {
    return "116f4420ea0459e5fc977d3ea8f73c46";
  }

  static const char* value(const ::gs_service::PosGPS&) { return value(); }
};

template<>
struct DataType< ::gs_service::PosGPS > {
  static const char* value()
  {
    return "gs_service/PosGPS";
  }

  static const char* value(const ::gs_service::PosGPS&) { return value(); }
};


// service_traits::MD5Sum< ::gs_service::PosGPSRequest> should match 
// service_traits::MD5Sum< ::gs_service::PosGPS > 
template<>
struct MD5Sum< ::gs_service::PosGPSRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gs_service::PosGPS >::value();
  }
  static const char* value(const ::gs_service::PosGPSRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gs_service::PosGPSRequest> should match 
// service_traits::DataType< ::gs_service::PosGPS > 
template<>
struct DataType< ::gs_service::PosGPSRequest>
{
  static const char* value()
  {
    return DataType< ::gs_service::PosGPS >::value();
  }
  static const char* value(const ::gs_service::PosGPSRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gs_service::PosGPSResponse> should match 
// service_traits::MD5Sum< ::gs_service::PosGPS > 
template<>
struct MD5Sum< ::gs_service::PosGPSResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gs_service::PosGPS >::value();
  }
  static const char* value(const ::gs_service::PosGPSResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gs_service::PosGPSResponse> should match 
// service_traits::DataType< ::gs_service::PosGPS > 
template<>
struct DataType< ::gs_service::PosGPSResponse>
{
  static const char* value()
  {
    return DataType< ::gs_service::PosGPS >::value();
  }
  static const char* value(const ::gs_service::PosGPSResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GS_SERVICE_MESSAGE_POSGPS_H
