// Generated by gencpp from file gs_service/AltResponse.msg
// DO NOT EDIT!


#ifndef GS_SERVICE_MESSAGE_ALTRESPONSE_H
#define GS_SERVICE_MESSAGE_ALTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gs_service
{
template <class ContainerAllocator>
struct AltResponse_
{
  typedef AltResponse_<ContainerAllocator> Type;

  AltResponse_()
    : altitude(0.0)  {
    }
  AltResponse_(const ContainerAllocator& _alloc)
    : altitude(0.0)  {
  (void)_alloc;
    }



   typedef float _altitude_type;
  _altitude_type altitude;





  typedef boost::shared_ptr< ::gs_service::AltResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gs_service::AltResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AltResponse_

typedef ::gs_service::AltResponse_<std::allocator<void> > AltResponse;

typedef boost::shared_ptr< ::gs_service::AltResponse > AltResponsePtr;
typedef boost::shared_ptr< ::gs_service::AltResponse const> AltResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gs_service::AltResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gs_service::AltResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gs_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': True, 'HasHeader': False}
// {'gs_service': ['/home/ubuntu/geoscan_ws/src/gs_service/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::gs_service::AltResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gs_service::AltResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gs_service::AltResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gs_service::AltResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gs_service::AltResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gs_service::AltResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gs_service::AltResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e65a95f8aa933dff5e33d16e05a9392";
  }

  static const char* value(const ::gs_service::AltResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e65a95f8aa933dfULL;
  static const uint64_t static_value2 = 0xf5e33d16e05a9392ULL;
};

template<class ContainerAllocator>
struct DataType< ::gs_service::AltResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gs_service/AltResponse";
  }

  static const char* value(const ::gs_service::AltResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gs_service::AltResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 altitude\n"
;
  }

  static const char* value(const ::gs_service::AltResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gs_service::AltResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.altitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AltResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gs_service::AltResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gs_service::AltResponse_<ContainerAllocator>& v)
  {
    s << indent << "altitude: ";
    Printer<float>::stream(s, indent + "  ", v.altitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GS_SERVICE_MESSAGE_ALTRESPONSE_H
