// Generated by gencpp from file gs_service/Gyro.msg
// DO NOT EDIT!


#ifndef GS_SERVICE_MESSAGE_GYRO_H
#define GS_SERVICE_MESSAGE_GYRO_H

#include <ros/service_traits.h>


#include <gs_service/GyroRequest.h>
#include <gs_service/GyroResponse.h>


namespace gs_service
{

struct Gyro
{

typedef GyroRequest Request;
typedef GyroResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Gyro
} // namespace gs_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gs_service::Gyro > {
  static const char* value()
  {
    return "33b4fb692079f88afc254f2cb9ee8d63";
  }

  static const char* value(const ::gs_service::Gyro&) { return value(); }
};

template<>
struct DataType< ::gs_service::Gyro > {
  static const char* value()
  {
    return "gs_service/Gyro";
  }

  static const char* value(const ::gs_service::Gyro&) { return value(); }
};


// service_traits::MD5Sum< ::gs_service::GyroRequest> should match 
// service_traits::MD5Sum< ::gs_service::Gyro > 
template<>
struct MD5Sum< ::gs_service::GyroRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gs_service::Gyro >::value();
  }
  static const char* value(const ::gs_service::GyroRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gs_service::GyroRequest> should match 
// service_traits::DataType< ::gs_service::Gyro > 
template<>
struct DataType< ::gs_service::GyroRequest>
{
  static const char* value()
  {
    return DataType< ::gs_service::Gyro >::value();
  }
  static const char* value(const ::gs_service::GyroRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gs_service::GyroResponse> should match 
// service_traits::MD5Sum< ::gs_service::Gyro > 
template<>
struct MD5Sum< ::gs_service::GyroResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gs_service::Gyro >::value();
  }
  static const char* value(const ::gs_service::GyroResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gs_service::GyroResponse> should match 
// service_traits::DataType< ::gs_service::Gyro > 
template<>
struct DataType< ::gs_service::GyroResponse>
{
  static const char* value()
  {
    return DataType< ::gs_service::Gyro >::value();
  }
  static const char* value(const ::gs_service::GyroResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GS_SERVICE_MESSAGE_GYRO_H
