// Generated by gencpp from file gs_service/InfoResponse.msg
// DO NOT EDIT!


#ifndef GS_SERVICE_MESSAGE_INFORESPONSE_H
#define GS_SERVICE_MESSAGE_INFORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gs_service
{
template <class ContainerAllocator>
struct InfoResponse_
{
  typedef InfoResponse_<ContainerAllocator> Type;

  InfoResponse_()
    : num()  {
    }
  InfoResponse_(const ContainerAllocator& _alloc)
    : num(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _num_type;
  _num_type num;





  typedef boost::shared_ptr< ::gs_service::InfoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gs_service::InfoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct InfoResponse_

typedef ::gs_service::InfoResponse_<std::allocator<void> > InfoResponse;

typedef boost::shared_ptr< ::gs_service::InfoResponse > InfoResponsePtr;
typedef boost::shared_ptr< ::gs_service::InfoResponse const> InfoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gs_service::InfoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gs_service::InfoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gs_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'gs_service': ['/home/ubuntu/geoscan_ws/src/gs_service/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::gs_service::InfoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gs_service::InfoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gs_service::InfoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gs_service::InfoResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gs_service::InfoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gs_service::InfoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gs_service::InfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8470232561560e383557c02344b87f7";
  }

  static const char* value(const ::gs_service::InfoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8470232561560e3ULL;
  static const uint64_t static_value2 = 0x83557c02344b87f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::gs_service::InfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gs_service/InfoResponse";
  }

  static const char* value(const ::gs_service::InfoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gs_service::InfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"string num\n"
;
  }

  static const char* value(const ::gs_service::InfoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gs_service::InfoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InfoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gs_service::InfoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gs_service::InfoResponse_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GS_SERVICE_MESSAGE_INFORESPONSE_H
