// Generated by gencpp from file gs_service/LpsPos.msg
// DO NOT EDIT!


#ifndef GS_SERVICE_MESSAGE_LPSPOS_H
#define GS_SERVICE_MESSAGE_LPSPOS_H

#include <ros/service_traits.h>


#include <gs_service/LpsPosRequest.h>
#include <gs_service/LpsPosResponse.h>


namespace gs_service
{

struct LpsPos
{

typedef LpsPosRequest Request;
typedef LpsPosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LpsPos
} // namespace gs_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gs_service::LpsPos > {
  static const char* value()
  {
    return "28576301d1e7ebfaeb880e74c20055fe";
  }

  static const char* value(const ::gs_service::LpsPos&) { return value(); }
};

template<>
struct DataType< ::gs_service::LpsPos > {
  static const char* value()
  {
    return "gs_service/LpsPos";
  }

  static const char* value(const ::gs_service::LpsPos&) { return value(); }
};


// service_traits::MD5Sum< ::gs_service::LpsPosRequest> should match 
// service_traits::MD5Sum< ::gs_service::LpsPos > 
template<>
struct MD5Sum< ::gs_service::LpsPosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gs_service::LpsPos >::value();
  }
  static const char* value(const ::gs_service::LpsPosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gs_service::LpsPosRequest> should match 
// service_traits::DataType< ::gs_service::LpsPos > 
template<>
struct DataType< ::gs_service::LpsPosRequest>
{
  static const char* value()
  {
    return DataType< ::gs_service::LpsPos >::value();
  }
  static const char* value(const ::gs_service::LpsPosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gs_service::LpsPosResponse> should match 
// service_traits::MD5Sum< ::gs_service::LpsPos > 
template<>
struct MD5Sum< ::gs_service::LpsPosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gs_service::LpsPos >::value();
  }
  static const char* value(const ::gs_service::LpsPosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gs_service::LpsPosResponse> should match 
// service_traits::DataType< ::gs_service::LpsPos > 
template<>
struct DataType< ::gs_service::LpsPosResponse>
{
  static const char* value()
  {
    return DataType< ::gs_service::LpsPos >::value();
  }
  static const char* value(const ::gs_service::LpsPosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GS_SERVICE_MESSAGE_LPSPOS_H
