// Generated by gencpp from file gs_service/LpsVelResponse.msg
// DO NOT EDIT!


#ifndef GS_SERVICE_MESSAGE_LPSVELRESPONSE_H
#define GS_SERVICE_MESSAGE_LPSVELRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gs_service
{
template <class ContainerAllocator>
struct LpsVelResponse_
{
  typedef LpsVelResponse_<ContainerAllocator> Type;

  LpsVelResponse_()
    : lpsVelX(0.0)
    , lpsVelY(0.0)
    , lpsVelZ(0.0)  {
    }
  LpsVelResponse_(const ContainerAllocator& _alloc)
    : lpsVelX(0.0)
    , lpsVelY(0.0)
    , lpsVelZ(0.0)  {
  (void)_alloc;
    }



   typedef float _lpsVelX_type;
  _lpsVelX_type lpsVelX;

   typedef float _lpsVelY_type;
  _lpsVelY_type lpsVelY;

   typedef float _lpsVelZ_type;
  _lpsVelZ_type lpsVelZ;





  typedef boost::shared_ptr< ::gs_service::LpsVelResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gs_service::LpsVelResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LpsVelResponse_

typedef ::gs_service::LpsVelResponse_<std::allocator<void> > LpsVelResponse;

typedef boost::shared_ptr< ::gs_service::LpsVelResponse > LpsVelResponsePtr;
typedef boost::shared_ptr< ::gs_service::LpsVelResponse const> LpsVelResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gs_service::LpsVelResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gs_service::LpsVelResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gs_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': True, 'HasHeader': False}
// {'gs_service': ['/home/ubuntu/geoscan_ws/src/gs_service/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::gs_service::LpsVelResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gs_service::LpsVelResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gs_service::LpsVelResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gs_service::LpsVelResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gs_service::LpsVelResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gs_service::LpsVelResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gs_service::LpsVelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "81c82ec0d0933ca8027062009ab83047";
  }

  static const char* value(const ::gs_service::LpsVelResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x81c82ec0d0933ca8ULL;
  static const uint64_t static_value2 = 0x027062009ab83047ULL;
};

template<class ContainerAllocator>
struct DataType< ::gs_service::LpsVelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gs_service/LpsVelResponse";
  }

  static const char* value(const ::gs_service::LpsVelResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gs_service::LpsVelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"float32 lpsVelX\n"
"float32 lpsVelY\n"
"float32 lpsVelZ\n"
;
  }

  static const char* value(const ::gs_service::LpsVelResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gs_service::LpsVelResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lpsVelX);
      stream.next(m.lpsVelY);
      stream.next(m.lpsVelZ);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LpsVelResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gs_service::LpsVelResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gs_service::LpsVelResponse_<ContainerAllocator>& v)
  {
    s << indent << "lpsVelX: ";
    Printer<float>::stream(s, indent + "  ", v.lpsVelX);
    s << indent << "lpsVelY: ";
    Printer<float>::stream(s, indent + "  ", v.lpsVelY);
    s << indent << "lpsVelZ: ";
    Printer<float>::stream(s, indent + "  ", v.lpsVelZ);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GS_SERVICE_MESSAGE_LPSVELRESPONSE_H
