// Generated by gencpp from file gs_service/LpsYaw.msg
// DO NOT EDIT!


#ifndef GS_SERVICE_MESSAGE_LPSYAW_H
#define GS_SERVICE_MESSAGE_LPSYAW_H

#include <ros/service_traits.h>


#include <gs_service/LpsYawRequest.h>
#include <gs_service/LpsYawResponse.h>


namespace gs_service
{

struct LpsYaw
{

typedef LpsYawRequest Request;
typedef LpsYawResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LpsYaw
} // namespace gs_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gs_service::LpsYaw > {
  static const char* value()
  {
    return "2160bf7632f25ad6dc7c5aab561198d4";
  }

  static const char* value(const ::gs_service::LpsYaw&) { return value(); }
};

template<>
struct DataType< ::gs_service::LpsYaw > {
  static const char* value()
  {
    return "gs_service/LpsYaw";
  }

  static const char* value(const ::gs_service::LpsYaw&) { return value(); }
};


// service_traits::MD5Sum< ::gs_service::LpsYawRequest> should match 
// service_traits::MD5Sum< ::gs_service::LpsYaw > 
template<>
struct MD5Sum< ::gs_service::LpsYawRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gs_service::LpsYaw >::value();
  }
  static const char* value(const ::gs_service::LpsYawRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gs_service::LpsYawRequest> should match 
// service_traits::DataType< ::gs_service::LpsYaw > 
template<>
struct DataType< ::gs_service::LpsYawRequest>
{
  static const char* value()
  {
    return DataType< ::gs_service::LpsYaw >::value();
  }
  static const char* value(const ::gs_service::LpsYawRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gs_service::LpsYawResponse> should match 
// service_traits::MD5Sum< ::gs_service::LpsYaw > 
template<>
struct MD5Sum< ::gs_service::LpsYawResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gs_service::LpsYaw >::value();
  }
  static const char* value(const ::gs_service::LpsYawResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gs_service::LpsYawResponse> should match 
// service_traits::DataType< ::gs_service::LpsYaw > 
template<>
struct DataType< ::gs_service::LpsYawResponse>
{
  static const char* value()
  {
    return DataType< ::gs_service::LpsYaw >::value();
  }
  static const char* value(const ::gs_service::LpsYawResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GS_SERVICE_MESSAGE_LPSYAW_H
