// Generated by gencpp from file gs_service/OrtResponse.msg
// DO NOT EDIT!


#ifndef GS_SERVICE_MESSAGE_ORTRESPONSE_H
#define GS_SERVICE_MESSAGE_ORTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gs_service
{
template <class ContainerAllocator>
struct OrtResponse_
{
  typedef OrtResponse_<ContainerAllocator> Type;

  OrtResponse_()
    : roll(0.0)
    , pitch(0.0)
    , azimuth(0.0)  {
    }
  OrtResponse_(const ContainerAllocator& _alloc)
    : roll(0.0)
    , pitch(0.0)
    , azimuth(0.0)  {
  (void)_alloc;
    }



   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _azimuth_type;
  _azimuth_type azimuth;





  typedef boost::shared_ptr< ::gs_service::OrtResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gs_service::OrtResponse_<ContainerAllocator> const> ConstPtr;

}; // struct OrtResponse_

typedef ::gs_service::OrtResponse_<std::allocator<void> > OrtResponse;

typedef boost::shared_ptr< ::gs_service::OrtResponse > OrtResponsePtr;
typedef boost::shared_ptr< ::gs_service::OrtResponse const> OrtResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gs_service::OrtResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gs_service::OrtResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gs_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': True, 'HasHeader': False}
// {'gs_service': ['/home/ubuntu/geoscan_ws/src/gs_service/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::gs_service::OrtResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gs_service::OrtResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gs_service::OrtResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gs_service::OrtResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gs_service::OrtResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gs_service::OrtResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gs_service::OrtResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b3c60a4574eaeb417260f557d541c25";
  }

  static const char* value(const ::gs_service::OrtResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b3c60a4574eaeb4ULL;
  static const uint64_t static_value2 = 0x17260f557d541c25ULL;
};

template<class ContainerAllocator>
struct DataType< ::gs_service::OrtResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gs_service/OrtResponse";
  }

  static const char* value(const ::gs_service::OrtResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gs_service::OrtResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"float32 roll\n"
"float32 pitch\n"
"float32 azimuth\n"
;
  }

  static const char* value(const ::gs_service::OrtResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gs_service::OrtResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.azimuth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OrtResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gs_service::OrtResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gs_service::OrtResponse_<ContainerAllocator>& v)
  {
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "azimuth: ";
    Printer<float>::stream(s, indent + "  ", v.azimuth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GS_SERVICE_MESSAGE_ORTRESPONSE_H
