// Generated by gencpp from file gs_service/PosGPSRequest.msg
// DO NOT EDIT!


#ifndef GS_SERVICE_MESSAGE_POSGPSREQUEST_H
#define GS_SERVICE_MESSAGE_POSGPSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gs_service
{
template <class ContainerAllocator>
struct PosGPSRequest_
{
  typedef PosGPSRequest_<ContainerAllocator> Type;

  PosGPSRequest_()
    : latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)  {
    }
  PosGPSRequest_(const ContainerAllocator& _alloc)
    : latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)  {
  (void)_alloc;
    }



   typedef float _latitude_type;
  _latitude_type latitude;

   typedef float _longitude_type;
  _longitude_type longitude;

   typedef float _altitude_type;
  _altitude_type altitude;





  typedef boost::shared_ptr< ::gs_service::PosGPSRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gs_service::PosGPSRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PosGPSRequest_

typedef ::gs_service::PosGPSRequest_<std::allocator<void> > PosGPSRequest;

typedef boost::shared_ptr< ::gs_service::PosGPSRequest > PosGPSRequestPtr;
typedef boost::shared_ptr< ::gs_service::PosGPSRequest const> PosGPSRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gs_service::PosGPSRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gs_service::PosGPSRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gs_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': True, 'HasHeader': False}
// {'gs_service': ['/home/ubuntu/geoscan_ws/src/gs_service/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::gs_service::PosGPSRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gs_service::PosGPSRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gs_service::PosGPSRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gs_service::PosGPSRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gs_service::PosGPSRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gs_service::PosGPSRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gs_service::PosGPSRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a2e11fb88a176ca38c3d01d3eaefff7a";
  }

  static const char* value(const ::gs_service::PosGPSRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa2e11fb88a176ca3ULL;
  static const uint64_t static_value2 = 0x8c3d01d3eaefff7aULL;
};

template<class ContainerAllocator>
struct DataType< ::gs_service::PosGPSRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gs_service/PosGPSRequest";
  }

  static const char* value(const ::gs_service::PosGPSRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gs_service::PosGPSRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 latitude\n"
"float32 longitude\n"
"float32 altitude\n"
"\n"
;
  }

  static const char* value(const ::gs_service::PosGPSRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gs_service::PosGPSRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PosGPSRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gs_service::PosGPSRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gs_service::PosGPSRequest_<ContainerAllocator>& v)
  {
    s << indent << "latitude: ";
    Printer<float>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<float>::stream(s, indent + "  ", v.longitude);
    s << indent << "altitude: ";
    Printer<float>::stream(s, indent + "  ", v.altitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GS_SERVICE_MESSAGE_POSGPSREQUEST_H
