(cl:in-package gs_vision-msg)
(cl:export '(TAG_FAMILY-VAL
          TAG_FAMILY
          TAG_ID-VAL
          TAG_ID
          HAMMING-VAL
          HAMMING
          GOODNESS-VAL
          GOODNESS
          DECISION_MARGIN-VAL
          DECISION_MARGIN
          CENTER_X-VAL
          CENTER_X
          CENTER_Y-VAL
          CENTER_Y
          X1-VAL
          X1
          Y1-VAL
          Y1
          X2-VAL
          X2
          Y2-VAL
          Y2
          X3-VAL
          X3
          Y3-VAL
          Y3
          X4-VAL
          X4
          Y4-VAL
          Y4
))